---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# clidatajp

<!-- badges: start -->
<!-- badges: end -->

clidatajpは，日本の気象庁(JMA)から取得した気候データを提供することを目的に開発しました．
気象庁から新たにデータをダウンロードすることも可能です．

## インストール

開発中のバージョンは，GitHubからダウンロード可能です．
また，clidatajpを使わずとも，手作業で気象庁から直接データをダウンロードすることもできます．

https://www.data.jma.go.jp/gmd/cpd/monitor/nrmlist/

``` r
  # CRAN
install.packages("clidatajp")

  # development
  # install.packages("devtools")
devtools::install_github("matutosi/clidatajp")
```

## 実行例

基本的な使い方は以下をご覧ください．

```{r example}
library(clidatajp)
library(tidyverse)

  # 観測地点とそのリンクのデータ
data(station_links)
station_links %>%
  dplyr::mutate("station" := stringi::stri_unescape_unicode(station))

  # 観測データ(日本，世界)
data(japan_climate)
japan_climate %>%
  dplyr::mutate_if(is.character, stringi::stri_unescape_unicode)

data(world_climate)
world_climate %>%
  dplyr::mutate_if(is.character, stringi::stri_unescape_unicode)

  # 新たにデータを取得する場合
station_links %>%
  `$`("url") %>%
  `[[`(1) %>%
  download_climate()
```

## 引用

Toshikazu Matsumura (2022) Tools for download climate data from Japan Meteorological Agency with R. https://github.com/matutosi/clidatajp/ .

松村 俊和 (2022) Rを使った気象協会からの観測データの取得ツール. https://github.com/matutosi/clidatajp/ .
