test_that("data nrow and ncol", {
  data(climate_world)
  data(climate_jp)
  data(station_links)
  expect_equal(nrow(climate_jp),     3768)
  expect_equal(ncol(climate_jp),       14)
  expect_equal(nrow(climate_world), 41328)
  expect_equal(ncol(climate_world),    11)
  expect_equal(nrow(station_links),  3444)
  expect_equal(ncol(station_links),     3)
})
